<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_ruangan extends CI_Model
{

    public $table = 'm_ruangan';
    public $id = 'id_ruangan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_ruangan,no_ruangan,nama_ruangan');
        $this->datatables->from('m_ruangan');
        //add this line for join
        //$this->datatables->join('table2', 'm_ruangan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('m_ruangan/read/$1'),'Read')." | ".anchor(site_url('m_ruangan/update/$1'),'Update')." | ".anchor(site_url('m_ruangan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_ruangan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ruangan', $q);
	$this->db->or_like('no_ruangan', $q);
	$this->db->or_like('nama_ruangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ruangan', $q);
	$this->db->or_like('no_ruangan', $q);
	$this->db->or_like('nama_ruangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Model_ruangan.php */
/* Location: ./application/models/Model_ruangan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-22 17:29:25 */
/* http://harviacode.com */