<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_barang extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_barang');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('m_barang/m_barang_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Model_barang->json();
    }

    public function read($id) 
    {
        $row = $this->Model_barang->get_by_id($id);
        if ($row) {
            $data = array(
		'id_barang' => $row->id_barang,
		'no_barang' => $row->no_barang,
		'nama_barang' => $row->nama_barang,
	    );
            $this->load->view('m_barang/m_barang_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_barang'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('m_barang/create_action'),
	    'id_barang' => set_value('id_barang'),
	    'no_barang' => set_value('no_barang'),
	    'nama_barang' => set_value('nama_barang'),
	);
        $this->load->view('m_barang/m_barang_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'no_barang' => $this->input->post('no_barang',TRUE),
		'nama_barang' => $this->input->post('nama_barang',TRUE),
	    );

            $this->Model_barang->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('m_barang'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Model_barang->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('m_barang/update_action'),
		'id_barang' => set_value('id_barang', $row->id_barang),
		'no_barang' => set_value('no_barang', $row->no_barang),
		'nama_barang' => set_value('nama_barang', $row->nama_barang),
	    );
            $this->load->view('m_barang/m_barang_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_barang'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_barang', TRUE));
        } else {
            $data = array(
		'no_barang' => $this->input->post('no_barang',TRUE),
		'nama_barang' => $this->input->post('nama_barang',TRUE),
	    );

            $this->Model_barang->update($this->input->post('id_barang', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('m_barang'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Model_barang->get_by_id($id);

        if ($row) {
            $this->Model_barang->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('m_barang'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_barang'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('no_barang', 'no barang', 'trim|required');
	$this->form_validation->set_rules('nama_barang', 'nama barang', 'trim|required');

	$this->form_validation->set_rules('id_barang', 'id_barang', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file M_barang.php */
/* Location: ./application/controllers/M_barang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-22 15:47:01 */
/* http://harviacode.com */